### ISSUE TITLE
Missing ERROR_CHAR fallback rule in lexer

### ISSUE THREAD

**Issue by sharwell** [mwpowellhtx/Kingdom.Protobuf#1]
The lexer needs the following rule added as the _last_ rule, otherwise unrecognized characters will be silently dropped as though they never existed in the input:

```
ERROR_CHAR : . ;
```

**Comment by mwpowellhtx** [comment]
@sharwell Re: your suggestions, I appreciate that. That would most likely help for clarity throughout as well.

**Comment by mwpowellhtx** [comment]
@sharwell :100: I'm not sure why the issue reared its ugly little head now, the rules in question have been in for at least a couple of iterations. That said, I'll take the victory! Thanks for the feedback.
